### ISSUE TITLE
Ability for a branch to be deployed to different appname through .yml file

### ISSUE THREAD

**Issue by OllieJennings** [boxxenapp/hubot-deploy#8]
Right now, if you deploy a branch of an app, and a `.yml` file in the repo, the branch will overnight this, instead you should be able to specify an `appname` for any branch other than master

**Comment by OllieJennings** [comment]
E.g. the yaml file would be:

```
deploy:
    heroku:
        master: (ref the branch)
            appname: foobar-123
        new-feature:
            appname: fooo-feature
        other: (fallback for all branch names)
            appname: foo-fallback
```
